### ISSUE TITLE
Register Error

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#107] opened 2016-11-10 23:57 UTC
When I try to register me as a new user I get this error. 
I'm on localhost, could be this related?

```
.../kirby/vendor/getkirby/toolkit/lib/email.php
  public $replyTo;
  public $subject;
  public $body;
 
  public function __construct($params = array()) {
    $options = a::merge(static::$defaults, $params);
    parent::__construct($options);
  }
 
  public function __set($key, $value) {
    $this->$key = $value;
  }
 
  /**
   * Validates the constructed email
   * to make sure it can be sent at all
   */
  public function validate() {
    if(!v::email($this->extractAddress($this->to)))      throw new Error('Invalid recipient', static::ERROR_INVALID_RECIPIENT);
    if(!v::email($this->extractAddress($this->from)))    throw new Error('Invalid sender', static::ERROR_INVALID_SENDER);
    if(!v::email($this->extractAddress($this->replyTo))) throw new Error('Invalid reply address', static::ERROR_INVALID_REPLY_TO);
    if(empty($this->subject))    throw new Error('Missing subject', static::ERROR_INVALID_SUBJECT);
    if(empty($this->body))       throw new Error('Missing body', static::ERROR_INVALID_BODY);
  }
 
  /**
```

**Comment by samnabi** [comment] 2016-11-11 00:57
What is the text of the error message?

**Comment by guidoferreyra** [comment] 2016-11-11 00:59
the text? Invalid Sender? The full text is what i've pasted on the previous message.

**Comment by samnabi** [comment] 2016-11-11 01:09
Hm, I'm not able to replicate this error. So the text above is in the main window of the Whoops dialog? And what is shown in the top-left corner?

**Comment by guidoferreyra** [comment] 2016-11-11 02:16
in the top left corner "Error (1) Invalid sender" and in the main window of Whoops the text Ive pasted above.

**Comment by guidoferreyra** [comment] 2016-11-12 19:46
The error it's produced when I input fake emails like aksdlas@gmail.com or the email field is the only one empty. When I input a valid email it works fine.

**Comment by samnabi** [comment] 2016-11-13 18:54
Since the error is "Invalid sender", I think the issue is that you're on localhost. Shopkit uses [$_SERVER['HTTP_HOST']](https://github.com/samnabi/shopkit/blob/master/site/plugins/shopkit/shopkit.php#L347) to build the "from" email address. Kirby's email function probably fails with a sender like noreply@localhost

I will look into this further and run some tests.

**Comment by guidoferreyra** [comment] 2016-11-13 22:22
Testing on the server: 
If I fill al the fields except email I get `Invalid recipient` on the upper left corner and in the main window. 

```
.../kirby/vendor/getkirby/toolkit/lib/email.php

public function __set($key, $value) {
    $this->$key = $value;
  }

  /**
   * Validates the constructed email
   * to make sure it can be sent at all
   */
  public function validate() {
    if(!v::email($this->extractAddress($this->to)))      throw new Error('Invalid recipient', static::ERROR_INVALID_RECIPIENT);
    if(!v::email($this->extractAddress($this->from)))    throw new Error('Invalid sender', static::ERROR_INVALID_SENDER);
    if(!v::email($this->extractAddress($this->replyTo))) throw new Error('Invalid reply address', static::ERROR_INVALID_REPLY_TO);
    if(empty($this->subject))    throw new Error('Missing subject', static::ERROR_INVALID_SUBJECT);
    if(empty($this->body))       throw new Error('Missing body', static::ERROR_INVALID_BODY);
  }

  /**
```

A workaround that I founded, is to create an account without email so the form thinks that the email is duplicate.

**Comment by samnabi** [comment] 2016-11-14 15:29
Why are you leaving the email address blank? Shopkit requires an email address when you register.

**Comment by guidoferreyra** [comment] 2016-11-14 19:57
I’m testing leaving the email field in blank because sometimes users don't fill everything by mistake. So, if a user doesn't fill this it gets the whoops error page.

**Comment by samnabi** [comment] 2016-11-15 16:14
Oh, okay. I'll look into that as a separate issue. It looks like the order of validation operations might be off in the `register.php` controller.

**Comment by samnabi** [comment] 2016-11-17 22:32
Okay, both of these issues are now fixed in the latest version of the `master` branch.

I removed the `username` field from the registration page, since Shopkit uses emails for login purposes. The username is now auto-generated from the email address. (Users will never see the username anyway).

There are now more informative error messages for invalid input on the Registration page.

And if you try to register on a server that can't send mail (like `localhost`), you'll get an informative error message instead of the Whoops error page.

![screen shot 2016-11-17 at 17 31 27](https://cloud.githubusercontent.com/assets/1731536/20410558/b14ed6a8-aceb-11e6-9a68-78265b6daf5c.png)

**Closed as completed by samnabi** 2016-11-17 22:32 UTC
Labels: bug
