### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#197] opened 2017-12-30 19:32 UTC
Hi Sam. Using the last version from the Master branch I get the following error when I confirm an Order.

In `plugins/shopkit/snippets/order.details.php`

Line 74
`<td style="text-align: right; vertical-align: top;"><?= formatPrice($txn->shipping()->value + $txn->shipping_additional()->value) ?></td>`

Best!

**Comment by HermesHarmony** [comment] 2018-01-11 18:02
Is there already a solution for this problem? 
The problem only occurs when the website is online. When I open it with the virtual server (MAMP) it works..

**Comment by guidoferreyra** [comment] 2018-01-11 18:06
In my case I get the error in MAMP too.

**Comment by guidoferreyra** [comment] 2018-01-17 15:00
@samnabi sorry for insist. Did you find a solution for this?

**Comment by samnabi** [comment] 2018-01-17 19:18
Sorry for the silence on my end. This is an error that comes up time and again in different parts of Shopkit.

The problem is, there are two values being added together. If one of those valeus is `null` or blank, we get this `non-numeric error` notice on some PHP setups.

It's not automatically treated as a zero.

I have patched this in previous issues by casting the values as floats:

`<td style="text-align: right; vertical-align: top;"><?= formatPrice((float)$txn->shipping()->value + (float) $txn->shipping_additional()->value) ?></td>`

You can do this as a hotfix.

However, I know this should be fixed in a more systemic way in the future.

**Closed as completed** 2018-04-15 17:42 UTC
Labels: bug
